# Generated by Django 3.2.25 on 2025-07-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Waiting for payment'), ('Processing', 'processing'), ('Shipped', 'Order shipped'), ('Delivered', 'Order successfully delivered')], default='Pending', max_length=50),
        ),
    ]
