# Generated by Django 3.2.25 on 2025-07-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Waiting for payment'), ('Processing', 'Processing'), ('Shipped', 'Order shipped'), ('Delivered', 'Order successfully delivered')], default='Pending', max_length=50),
        ),
    ]
